#generate keypair for user nuclei
#ansible app -m shell -a "ssh-keygen -q -b 2048 -t rsa -N '' -C 'creating SSH' -f /home/nuclei/.ssh/id_rsa_nuclei creates='/home/nuclei/.ssh/id_rsa_arachni'" -i ol9_dasty_box -b – become-user=nuclei
#ansible app -m shell -a "ls -lrt  /home/nuclei/.ssh/id_rsa_nuclei" -i ol9_dasty_box -b – become-user=nuclei
#ansible app -m fetch -a "src='/home/nuclei/.ssh/id_rsa_nuclei.pub' dest='buffer/{{inventory_hostname}}-id_rsa_nuclei.pub' flat='yes'" -i ol9_dasty_box -b – become-user=nuclei
#ansible app -m authorized_key -a "user='nuclei' state='p
---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account, ssh keys
      shell: |
        groupadd -r nuclei
        useradd -r -g nuclei nuclei -m
        mkdir -p /home/nuclei/.ssh
        ssh-keygen -q -b 2048 -t rsa -N '' -C 'creating SSH' -f /home/nuclei/.ssh/id_rsa_nuclei creates='/home/nuclei/.ssh/id_rsa_nuclei'
        mv /home/nuclei/id_rsa_nuclei.pub /home/nuclei/.ssh/authorized_keys
        chmod 0600 /home/nuclei/.ssh/authorized_keys
        chmod 0700 /home/nuclei/.ssh
        chown -R nuclei:nuclei /home/nuclei
