---
- hosts: ol9_dasty_box
  gather_facts: no
  become: yes
  become_user: nuclei
  tasks:
    - name: "Nuclei Scans"
      shell: |
        DATE=$(date +"%Y%m%d")
        MODE=http
        TARGET=testhtml5.vulnweb.com
        THREADS=35
        RESULT_DIR=/home/nuclei
        mkdir -p ${RESULT_DIR}/scans
        podman run --rm -v /etc/localtime:/etc/localtime:ro -it --name nuclei -d nuclei:v1.0
        podman network create nuclei-net
        podman network connect nuclei-net nuclei
        podman exec nuclei nuclei -ut
        podman exec nuclei nuclei -c $THREADS -ni -u ${MODE}://${TARGET} -o /home/nuclei/nuclei-${MODE}-${TARGET}-${DATE}.log
        podman cp nuclei:/home/nuclei $RESULT_DIR/scans
