version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    title: "Clone main repository..."
    repo: "rw-repo/_tooling_main/dast/caido"
    revision: "release"
    stage: "clone"
  build:
    title: "Building podman Image"
    type: "build"
    image_name: "caido:release"
    tag: "release"
    Dockerfile: "Dockerfile"
    stage: "build"
  runJob:
    title: "Deploying Nomad job"
    image: quay.io/rootshifty/caido
    stage: deploy
    commands:
      - nomad run caido-service-job.hcl  
