tls:
  certificates:
    - certFile: /etc/certs/<web service name>.<tld name>.certificate
      keyFile: /etc/certs/<web service name>.<tld name>.key
      stores:
        - default
      service: <enter service name>
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
#    tlsv13force:
#      minVersion: VersionTLS13
#      curvePreferences:
#        - CurveP521
#        - CurveP384
#      sniStrict: true
  stores:
    default:
      defaultCertificate:
        - certFile: /etc/certs/<web service name>.<tld name>.certificate
          keyFile: /etc/certs/<web service name>.<tld name>.key
