service:
  type: LoadBalancer
  port: 443

image:
  tag: latest

resources: {}
  # limits:
  #   cpu: 
  #   memory: 
  # requests:
  #   cpu: 
  #   memory: 

nessus:
  activation_code: ""
  username: ""
  password: ""
  auto_update: ""
