version: '3'

services:

  caido:
    build:
      context: caido/
    container_name: caido
    hostname: caido
    security_opt:
      - no-new-privileges:true
    volumes:
      - caido:/home/caido/.local/share/caido:Z
    ports:
      - "7000:8080"
    restart: unless-stopped
    networks:
      - caido

networks:
  caido:

volumes:
  caido:
