version: '3'

services:
  web:
    build: .
    ports:
      - '5000:80'
    volumes:
      - .:/app
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s