---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: caido-vol
provisioner: k8s.io/minikube-hostpath
parameters:
 {}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
