version: '3'

networks:
  hyperdx:
  
x-common-vars-apps: &common-vars-apps
  security_opt:
    - no-new-privileges:true
  env_file:
    - .env
  networks:
    - hyperdx
  restart: unless-stopped

services:
  miner:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-miner
    container_name: hdx-oss-miner
    environment:
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      HYPERDX_ENABLE_ADVANCED_NETWORK_CAPTURE: 1
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      OTEL_SERVICE_NAME: hdx-oss-miner
    ports:
      - 5123:5123

  hostmetrics:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-hostmetrics
    container_name: hdx-oss-hostmetrics
    environment:
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      OTEL_SERVICE_NAME: hostmetrics

  ingestor:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-ingestor
    container_name: hdx-oss-ingestor
    volumes:
      - .volumes/ingestor_data:/var/lib/vector
    ports:
      - 8002:8002 # http-generic
      - 8686:8686 # healthcheck
    environment:
      RUST_BACKTRACE: full
      VECTOR_LOG: ${HYPERDX_LOG_LEVEL}
      VECTOR_OPENSSL_LEGACY_PROVIDER: 'false'

  redis:
    <<: *common-vars-apps
    image: redis:7.0.11-alpine
    container_name: hdx-oss-redis
    volumes:
      - .volumes/redis:/data
    ports:
      - 6379:6379

  db:
    <<: *common-vars-apps
    image: mongo:5.0.14-focal
    container_name: hdx-oss-db
    volumes:
      - .volumes/db:/data/db
    ports:
      - 27017:27017

  otel-collector:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-otel-collector
    container_name: hdx-oss-otel-collector
    environment:
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
    ports:
      - '13133:13133' # health_check extension
      - '1888:1888' # pprof extension
      - '24225:24225' # fluentd receiver
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
      - '55679:55679' # zpages extension
      - '8888:8888' # metrics extension
      - '9411:9411' # zipkin

  aggregator:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-api
    container_name: hdx-oss-aggregator
    ports:
      - 8001:8001
    environment:
      APP_TYPE: 'aggregator'
      CLICKHOUSE_HOST: http://ch-server:8123
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_AGG_PASSWORD}
      CLICKHOUSE_USER: aggregator
      FRONTEND_URL: ${HYPERDX_APP_URL}:${HYPERDX_APP_PORT} # need to be localhost (CORS)
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      MONGO_URI: 'mongodb://db:27017/hyperdx'
      NODE_ENV: development
      PORT: 8001
      REDIS_URL: redis://redis:6379
      SERVER_URL: ${HYPERDX_API_URL}:${HYPERDX_API_PORT}
    depends_on:
      - db
      - redis
      - ch-server

  task-check-alerts:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-api
    container_name: hdx-oss-task-check-alerts
    entrypoint: 'node'
    command: './build/tasks/index.js check-alerts'
    environment:
      APP_TYPE: 'scheduled-task'
      CLICKHOUSE_HOST: http://ch-server:8123
      CLICKHOUSE_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_WRK_PASSWORD}
      CLICKHOUSE_USER: worker
      FRONTEND_URL: ${HYPERDX_APP_URL}:${HYPERDX_APP_PORT} # need to be localhost (CORS)
      HDX_NODE_ADVANCED_NETWORK_CAPTURE: 1
      HDX_NODE_BETA_MODE: 0
      HDX_NODE_CONSOLE_CAPTURE: 1
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      INGESTOR_API_URL: 'http://ingestor:8002'
      MINER_API_URL: 'http://miner:5123'
      MONGO_URI: 'mongodb://db:27017/hyperdx'
      NODE_ENV: development
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      OTEL_SERVICE_NAME: 'hdx-oss-task-check-alerts'
      REDIS_URL: redis://redis:6379
    depends_on:
      - ch-server
      - db
      - redis

  api:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-api
    container_name: hdx-oss-api
    ports:
      - ${HYPERDX_API_PORT}:${HYPERDX_API_PORT}
    environment:
      AGGREGATOR_API_URL: 'http://aggregator:8001'
      APP_TYPE: 'api'
      CLICKHOUSE_HOST: http://ch-server:8123
      CLICKHOUSE_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_API_PASSWORD}
      CLICKHOUSE_USER: api
      EXPRESS_SESSION_SECRET: 'hyperdx is cool 👋'
      FRONTEND_URL: ${HYPERDX_APP_URL}:${HYPERDX_APP_PORT} # need to be localhost (CORS)
      HDX_NODE_ADVANCED_NETWORK_CAPTURE: 1
      HDX_NODE_BETA_MODE: 1
      HDX_NODE_CONSOLE_CAPTURE: 1
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
      INGESTOR_API_URL: 'http://ingestor:8002'
      MINER_API_URL: 'http://miner:5123'
      MONGO_URI: 'mongodb://db:27017/hyperdx'
      NODE_ENV: development
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      OTEL_SERVICE_NAME: 'hdx-oss-api'
      PORT: ${HYPERDX_API_PORT}
      REDIS_URL: redis://redis:6379
      SERVER_URL: ${HYPERDX_API_URL}:${HYPERDX_API_PORT}
      USAGE_STATS_ENABLED: ${USAGE_STATS_ENABLED:-true}
    depends_on:
      - ch-server
      - db
      - redis

  app:
    <<: *common-vars-apps
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-app
    container_name: hdx-oss-app
    ports:
      - ${HYPERDX_APP_PORT}:${HYPERDX_APP_PORT}
    environment:
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      NODE_ENV: development
      PORT: ${HYPERDX_APP_PORT}
    depends_on:
      - api

  ch-server:
    <<: *common-vars-apps
    image: clickhouse/clickhouse-server:23.7.1-alpine
    container_name: hdx-oss-ch-server
    ports:
      - 8123:8123 # http api
      - 9000:9000 # native
    environment:
      # default settings
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./local/config.xml:/etc/clickhouse-server/config.xml
      - ./local/users.xml:/etc/clickhouse-server/users.xml
      - .volumes/ch_data:/var/lib/clickhouse
      - .volumes/ch_logs:/var/log/clickhouse-server