---
- hosts: ol9_dasty_box
  gather_facts: no
  become: yes
  become_user: owasp-zap
  tasks:
    - name: create build directory
      file:
        path: /home/owasp-zap/build-container
        state: directory
        owner: owasp-zap
        group: owasp-zap
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/owasp-zap/Dockerfile
        dest: /home/owasp-zap/build-container/Dockerfile
        owner: owasp-zap
        group: owasp-zap
        mode: '0644'
    - name: build container image
      docker_image:
        name: owasp-zap:v1.0
        build:
          path: /home/owasp-zap/build-container/Dockerfile
          source: build
        state: present
