---
apiVersion: v1
kind: Secret
metadata:
 name: traefik-certs
 labels:
   k8s-app: traefik-controller
type: kubernetes.io/tls
data:
#cat traefik.nessus.io.crt | base64 -w0
#cat traefik.nessus.io.key | base64 -w0
 traefik.nessus.io.crt: 
 traefik.nessus.io.key: 