# syntax=docker/dockerfile:1
# AWS cdk install
ARG repo="docker.io" \
    base_image="node:20.9.0-alpine3.18" \
    image_hash="807e66e2bee193961c9642bb1157d77a61747bf76737ca786da45b10749dcb42"
    
FROM ${repo}/${base_image}@sha256:${image_hash}

ENV AWSCDK_VERSION="2.103.1" \
    GLIBC_VER="2.35-r1" \
    AWS_PAGER=""

RUN \
    apk add --no-cache --update \
      python3 \
      python3-dev \
      git \
      jq; \
    python3 -m ensurepip; \
    pip3 install --upgrade pip; \
    pip3 install \
      boto3 \
      json-spec \
      yamllint; \
    apk add --no-cache \
      binutils \
      curl
      unzip; \
    curl -sL https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub; \
    curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-${GLIBC_VER}.apk; \
    curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-bin-${GLIBC_VER}.apk; \
    apk add --force-overwrite --no-cache \
      glibc-${GLIBC_VER}.apk \
      glibc-bin-${GLIBC_VER}.apk; \
    curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip; \
    unzip awscliv2.zip; \
    aws/install; \
    rm -rf \
      awscliv2.zip \
      aws \
      /usr/local/aws-cli/v2/*/dist/aws_completer \
      /usr/local/aws-cli/v2/*/dist/awscli/data/ac.index \
      /usr/local/aws-cli/v2/*/dist/awscli/examples; \
    apk del --no-network \
      binutils \
      curl; \
    rm glibc-${GLIBC_VER}.apk; \
    rm glibc-bin-${GLIBC_VER}.apk; \
    rm -rf /var/cache/apk/*

RUN npm i --location=global npm
RUN npm i --location=global aws-cdk@${AWSCDK_VERSION}
