tls:
  certificates:
    #obtain a proper certificate
    #placeholder names, this is for your own cert versus the acme route.
    - certFile: "/traefik/certs/apifw.testing.io.pem"
      keyFile: "/traefik/certs/apifw.testing.io-key.pem"
      stores:
        - default
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  stores:
    default:
      defaultCertificate:
        certFile: "/traefik/certs/apifw.testing.io.pem"
        keyFile: "/traefik/certs/apifw.testing.io-key.pem"
