tls:
  certificates:
    - certFile: "/traefik/certs/nessus.testing.io.crt"
      keyFile: "/traefik/certs/nessus.testing.io.key"
      stores:
        - default
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
#     tlsv13force:
#       minVersion: VersionTLS13
# https://pkg.go.dev/crypto/tls#CurveID
#       curvePreferences:
#         - CurveP521
#         - CurveP384
#     sniStrict: true
  stores:
    default:
      defaultCertificate:
        certFile: "/traefik/certs/nessus.testing.io.crt"
        keyFile: "/traefik/certs/nessus.testing.io.key"
  
