#global:
#  checkNewVersion: true
#  sendAnonymousUsage: false
#api:
#  insecure: false
#  dashboard: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    swarmMode: false
    network: tenable
  file:
    directory: /etc/traefik/dynamic
    watch: true
#serversTransport:
#  insecureSkipVerify: true
#certificatesResolvers:
#  le-staging:
#    acme:
      # certificates will be generate with the staging ACME premium account
#      email: enter.your@email.com
#      httpChallenge:
        # used during the challenge
#        entryPoint: web
#  le-prod:
#    acme:
      # certificates will be generate with the production ACME premium account
#      email: enter.your@email.com
#      httpChallenge:
        # used during the challenge
#        entryPoint: web
#      tlsChallenge: {}
log:
  filePath: "/var/log/traefik/nessus/traefik.log"
  format: json
  level: INFO
accessLog:
  filePath: "/var/log/traefik/nessus/access.log"
  format: json
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"
#experimental:
#  plugins:
#    plugin-log4shell:
#      moduleName: "github.com/traefik/plugin-log4shell"
#      version: "v0.1.2"
#    fail2ban:
#      moduleName: "github.com/tomMoulard/fail2ban"
#      version: "v0.6.6"
#    crowdsec-bouncer-traefik-plugin:
#      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
#      version: "v1.1.2"
