apply_library_patches: true
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: falcon-streaming
model_type: custom
requirements:
- torch==2.0.1
- peft==0.4.0
- scipy==1.11.1
- sentencepiece==1.11.1
- accelerate==0.21.0
- bitsandbytes==0.41.1
- einops==0.6.1
- transformers==4.31.0
resources:
  use_gpu: true
  cpu: "3"
  memory: 14Gi
  accelerator: A10G
secrets: {}
spec_version: '2.0'
system_packages: []
